version: 1.0.3.{build}
os: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: './ExtendedVersion.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./ExtendedVersion/ExtendedVersion.csproj --verbosity m
build_script:
  - cmd: dotnet publish -c Release
artifacts:
 - path: 'ExtendedVersion\bin\Debug\netcoreapp2.1\publish'
   name: ExtendedVersion
   type: WebDeployPackage
deploy: off