version: 1.0.3.{build}
os: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./ExtendedVersion/ExtendedVersion.csproj --verbosity m
build_script:
  - cmd: dotnet publish -c Release
after_build:
  - cmd: dotnet pack ./ExtendedVersion/ExtendedVersion.csproj --configuration Release
artifacts:
 - path: '.\ExtendedVersion\bin\Release\netcoreapp2.1\publish'
   name: ExtendedVersion
   type: WebDeployPackage
 - path: '*.nupkg'
   name: nuget_package
deploy:
  - provider: NuGet
    api_key:
      secure: 7iJJVXMbGnaDbwumUb6NlYmNBXhHWYEON8qv17eEsCPySOJ+ngrj7N29rpy/BKc9
    skip_symbols: false
    artifact: nuget_package
    on:
      branch: master