version: 1.0.3.{build}
os: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: 'ExtendedVersion\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
  - ps: nuget restore
build:
  project: ExtendedVersion.sln
artifacts:
- path: '*.nupkg'
  name: nuget_package
deploy:
  - provider: NuGet
    api_key:
      secure: 7iJJVXMbGnaDbwumUb6NlYmNBXhHWYEON8qv17eEsCPySOJ+ngrj7N29rpy/BKc9
    skip_symbols: false
    artifact: nuget_package
    on:
      branch: master